### ISSUE TITLE
About the phaser version.

### ISSUE THREAD

**Issue by Kharhamel** [workadventure-xce/workadventure-xce#19]
Hello

In thecodingmachine/workadventure, Phaser is still in version 3.24.1. Last time we tried to upgrade to 3.51, we started getting reports of crash from some mac users. Since we didn't have any idea how to fix that, we actually downgraded back to 3.24, and now we don't get crashes anymore. But now we are stuck.

I see that this fork uses the newest version of Phaser. Did you get similar problems? Do you have a lot of  mac users?

**Comment by tabascoeye** [comment]
we never heard of total crashes like you had reported.
I use a mid2015 macbook pro and I know of people using an M1 mac with BigSur, not having any problems.

You also commented out many code places, so maybe it was not only the phaser downgrade?!

==> so far it works for us and given the number of events and users we had, there should have been complaints ;)

**Comment by tabascoeye** [comment]
...or it was only some in-between version of phaser which we also no longer use?!

**Comment by pizkaz** [comment]
Hmm.. thing is: XCE is running on a few small servers, maybe more than a few, but - at least to my knowledge - there is no instance that has even a fraction of the users on workadventu.re. Also people are not paying to use XCE, so they might refrain from complaining.
What I'm trying to say: If crashes happen, I doubt that we would notice them.

That being said: I know that a few Mac users use "my" instance. Although there are complaints about laptops getting seriously warm, I am not aware of any BSODs caused by XCE.

**Comment by Kharhamel** [comment]
Yes WA heating up laptops is pretty common too, and it is probably linked to the macos crashes. Still weird that the os couldn't kill the browser before shutting down.

We will probably try again to upgrade, hoping it won't be the same, but like you said: people are much angrier once they've paid :)

Anyway thanks for the feedback.
